#Para lograr mi objetivo del ejetucable banco.exe hago esto
banco.exe: banco.o funciones.o 
	gcc banco.o funciones.o -o banco.exe

#Para lograr el objetivo del objeto de funciones.o hago esto:
funciones.o: funciones.c
	gcc -c funciones.c

#Para lograr el objetivo del objeto banco.o hago esto:
banco.o: banco.c
	gcc -c banco.c