#Para lograr mi objetivo del ejecutable formulas.exe hago esto

listaLIFO2.exe: listaLIFO2.o funciones.o defTipos.h
	gcc listaLIFO2.o funciones.o -o listaLIFO2.exe 

#Para lograr el objetivo del objeto formulas.o hago esto 

listaLIFO2.o: listaLIFO2.c 
	gcc -c listaLIFO2.c


funciones.o: funciones.c 
	gcc -c funciones.c