#Para lograr mi objetivo del ejecutable formulas.exe hago esto

circular.exe: circular.o funciones.o defcircular.h
	gcc circular.o funciones.o -o circular.exe 

#Para lograr el objetivo del objeto formulas.o hago esto 

circular.o: circular.c 
	gcc -c circular.c

funciones.o: funciones.c 
	gcc -c funciones.c