#Para lograr mi objetivo del ejecutable formulas.exe hago esto

listaFIFO.exe: listaFIFO.o funciones.o defFIFO.h
	gcc listaFIFO.o funciones.o -o listaFIFO.exe 

#Para lograr el objetivo del objeto formulas.o hago esto 

listaFIFO.o: listaFIFO.c 
	gcc -c listaFIFO.c


funciones.o: funciones.c 
	gcc -c funciones.c