#Para lograr mi objetivo del ejecutable formulas.exe hago esto

autos.exe: autos.o funciones.o tipos.h
	gcc autos.o funciones.o -o autos.exe 

#Para lograr el objetivo del objeto formulas.o hago esto 

autos.o: autos.c 
	gcc -c autos.c

funciones.o: funciones.c 
	gcc -c funciones.c