#Para lograr mi objetivo del ejecutable formulas.exe hago esto

ejecutable.exe: apuntArreglos.o darResultados.o incluido.h
	gcc apuntArreglos.o darResultados.o -o apuntArreglos.exe 

#Para lograr el objetivo del objeto formulas.o hago esto 

formulas.o: apuntArreglos.c 
	gcc -c apuntArreglos.c

#Para lograr el objetivo del objeto funciones1.o hago esto

funciones1.o: darResultados.c
	gcc -c darResultados.c 
