#Para lograr mi objetivo del ejecutable formulas.exe hago esto

grupoAlumnos.exe: grupoAlumnos.o capturarAlumnos.o defTipos.h
	gcc grupoAlumnos.o capturarAlumnos.o -o grupoAlumnos.exe 

#Para lograr el objetivo del objeto formulas.o hago esto 

grupoAlumnos.o: grupoAlumnos.c 
	gcc -c grupoAlumnos.c

#Para lograr el objetivo del objeto funciones1.o hago esto

capturarAlumnos.o: capturarAlumnos.c 
	gcc -c capturarAlumnos.c