#Para lograr mi objetivo del ejecutable formulas.exe hago esto

actualizarDatos.exe: actualizarDatos.o capturarAlumnos.o defTipos.h
	gcc actualizarDatos.o capturarAlumnos.o -o actualizarDatos.exe 

#Para lograr el objetivo del objeto formulas.o hago esto 

actualizarDatos.o: actualizarDatos.c 
	gcc -c actualizarDatos.c

#Para lograr el objetivo del objeto funciones1.o hago esto

capturarAlumnos.o: capturarAlumnos.c 
	gcc -c capturarAlumnos.c