#Para lograr mi objetivo del ejetucable canes.exe hago esto
canes.exe: canes.o funciones.o 
	gcc canes.o funciones.o -o canes.exe

#Para lograr el objetivo del objeto de funciones.o hago esto:
funciones.o: funciones.c
	gcc -c funciones.c

#Para lograr el objetivo del objeto canes.o hago esto:
canes.o: canes.c
	gcc -c canes.c