#Para lograr mi objetivo del ejecutable formulas.exe hago esto

alumnos.exe: alumnos.o funciones.o tipos.h
	gcc alumnos.o funciones.o -o alumnos.exe 

#Para lograr el objetivo del objeto formulas.o hago esto 

alumnos.o: alumnos.c 
	gcc -c alumnos.c


funciones.o: funciones.c 
	gcc -c funciones.c