#Para lograr mi objetivo del ejecutable palabras.exe hago esto

palabras.exe: palabras.o funciones.o misInluidos.h
	gcc palabras.o funciones.o -o palabras.exe 

#Para lograr el objetivo del objeto palabras.o hago esto 

palabras.o: palabras.c 
	gcc -c palabras.c

#Para lograr el objetivo del objeto funciones1.o hago esto

funciones.o: funciones.c 
	gcc -c funciones.c
