#Para lograr mi objetivo del ejecutable formulas.exe hago esto

cafe.exe: cafe.o funciones.o tipos.h
	gcc cafe.o funciones.o -o cafe.exe 

#Para lograr el objetivo del objeto formulas.o hago esto 

cafe.o: cafe.c 
	gcc -c cafe.c


funciones.o: funciones.c 
	gcc -c funciones.c