#Para lograr mi objetivo del ejetucable tienda.exe hago esto

tienda.exe: tienda.o funciones.o tiposTienda.h
	gcc tienda.o funciones.o -o tienda.exe

#Para lograr el objetivo del objeto tienda.o hago esto:
tienda.o: tienda.c
	gcc -c tienda.c
	
#Para lograr el objetivo del objeto de funciones.o hago esto:
funciones.o: funciones.c
	gcc -c funciones.c
