#Para lograr mi objetivo del ejecutable formulas.exe hago esto

invertirFrase.exe: invertirFrase.o funciones.o tipos.h
	gcc invertirFrase.o funciones.o -o invertirFrase.exe 

#Para lograr el objetivo del objeto formulas.o hago esto 

invertirFrase.o: invertirFrase.c 
	gcc -c invertirFrase.c


funciones.o: funciones.c 
	gcc -c funciones.c